#-----------------------------------------------------------------------
#
#   applicaton-common : Default Common Configuation
#   kubernetes PV(Persistent Volume) : /DATA 
#   
#-----------------------------------------------------------------------

spring:
  config:
    activate:
      on-profile: local

props:
  common:
    baseFilePath: /Users/rurony/DATA/
    edgeSwPath: files/edge_sw
  
---
 
spring:
  config:
    activate:
      on-profile: dev

props:
  common:
    baseFilePath: /DATA/
    edgeSwPath: files/edge_sw
 
---
 
spring:
  config:
    activate:
      on-profile: prod

props:
  common:
    baseFilePath: /DATA/
    edgeSwPath: files/edge_sw
